name: Trigger Website Deploy

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    # Ref: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event.
    steps:
      - name: Trigger Workflow in `agustinbravop/wafrre-website`
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/agustinbravop/wafrre-website/dispatches \
            -d '{"event_type": "trigger-workflow"}'
